### ISSUE TITLE
cannot import name 'delete_db' from 'database'

### ISSUE THREAD

**Issue by developan** [uysalemre/Python-Flask-Sqlite-RestApi-WebApp#13]
when i run python server.py ,
`(venv) (master)⚡ % python server.py                                                                                                         /data/tools/allone/www
Traceback (most recent call last):
  File "server.py", line 5, in <module>
    from database import db_session,init_db,delete_db
ImportError: cannot import name 'delete_db' from 'database' (/data/www/database.py)`

root document has a database.py,
my python version is 3.7.4

**Comment by uysalemre** [comment]
delete_db function added
by the way you  don't need test files you can delete it and its dependencies. Also you can delete delete_db calls from server.py if you don't need a new db for each run for your application.
I will take a look at everything in this project and commit changes ASAP.

**Comment by uysalemre** [comment]
removed test directory and changed application to normal form, requirements.txt added so app is working now. Closing this issue.
